/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TurmasIndexRouteImport } from './routes/turmas/index'
import { Route as InscritosIndexRouteImport } from './routes/inscritos/index'
import { Route as TurmasIdRouteImport } from './routes/turmas/$id'
import { Route as InscritosNovoRouteImport } from './routes/inscritos/novo'
import { Route as InscritosIdadesRouteImport } from './routes/inscritos/idades'
import { Route as InscritosIdRouteImport } from './routes/inscritos/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasIndexRoute = TurmasIndexRouteImport.update({
  id: '/turmas/',
  path: '/turmas/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscritosIndexRoute = InscritosIndexRouteImport.update({
  id: '/inscritos/',
  path: '/inscritos/',
  getParentRoute: () => rootRouteImport,
} as any)
const TurmasIdRoute = TurmasIdRouteImport.update({
  id: '/turmas/$id',
  path: '/turmas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InscritosNovoRoute = InscritosNovoRouteImport.update({
  id: '/inscritos/novo',
  path: '/inscritos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const InscritosIdadesRoute = InscritosIdadesRouteImport.update({
  id: '/inscritos/idades',
  path: '/inscritos/idades',
  getParentRoute: () => rootRouteImport,
} as any)
const InscritosIdRoute = InscritosIdRouteImport.update({
  id: '/inscritos/$id',
  path: '/inscritos/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/inscritos/$id': typeof InscritosIdRoute
  '/inscritos/idades': typeof InscritosIdadesRoute
  '/inscritos/novo': typeof InscritosNovoRoute
  '/turmas/$id': typeof TurmasIdRoute
  '/inscritos/': typeof InscritosIndexRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/inscritos/$id': typeof InscritosIdRoute
  '/inscritos/idades': typeof InscritosIdadesRoute
  '/inscritos/novo': typeof InscritosNovoRoute
  '/turmas/$id': typeof TurmasIdRoute
  '/inscritos': typeof InscritosIndexRoute
  '/turmas': typeof TurmasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/inscritos/$id': typeof InscritosIdRoute
  '/inscritos/idades': typeof InscritosIdadesRoute
  '/inscritos/novo': typeof InscritosNovoRoute
  '/turmas/$id': typeof TurmasIdRoute
  '/inscritos/': typeof InscritosIndexRoute
  '/turmas/': typeof TurmasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/inscritos/$id'
    | '/inscritos/idades'
    | '/inscritos/novo'
    | '/turmas/$id'
    | '/inscritos/'
    | '/turmas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/inscritos/$id'
    | '/inscritos/idades'
    | '/inscritos/novo'
    | '/turmas/$id'
    | '/inscritos'
    | '/turmas'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/inscritos/$id'
    | '/inscritos/idades'
    | '/inscritos/novo'
    | '/turmas/$id'
    | '/inscritos/'
    | '/turmas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  InscritosIdRoute: typeof InscritosIdRoute
  InscritosIdadesRoute: typeof InscritosIdadesRoute
  InscritosNovoRoute: typeof InscritosNovoRoute
  TurmasIdRoute: typeof TurmasIdRoute
  InscritosIndexRoute: typeof InscritosIndexRoute
  TurmasIndexRoute: typeof TurmasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas/': {
      id: '/turmas/'
      path: '/turmas'
      fullPath: '/turmas/'
      preLoaderRoute: typeof TurmasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscritos/': {
      id: '/inscritos/'
      path: '/inscritos'
      fullPath: '/inscritos/'
      preLoaderRoute: typeof InscritosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turmas/$id': {
      id: '/turmas/$id'
      path: '/turmas/$id'
      fullPath: '/turmas/$id'
      preLoaderRoute: typeof TurmasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscritos/novo': {
      id: '/inscritos/novo'
      path: '/inscritos/novo'
      fullPath: '/inscritos/novo'
      preLoaderRoute: typeof InscritosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscritos/idades': {
      id: '/inscritos/idades'
      path: '/inscritos/idades'
      fullPath: '/inscritos/idades'
      preLoaderRoute: typeof InscritosIdadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscritos/$id': {
      id: '/inscritos/$id'
      path: '/inscritos/$id'
      fullPath: '/inscritos/$id'
      preLoaderRoute: typeof InscritosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  InscritosIdRoute: InscritosIdRoute,
  InscritosIdadesRoute: InscritosIdadesRoute,
  InscritosNovoRoute: InscritosNovoRoute,
  TurmasIdRoute: TurmasIdRoute,
  InscritosIndexRoute: InscritosIndexRoute,
  TurmasIndexRoute: TurmasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
